-- Port of provided SQLite schema to Postgres (Supabase)
-- plus order_predictions + views to simplify app/scoring queries.

-- Ensure we can create helper extensions if needed later.
-- (Kept minimal; no extensions required for this project.)

create table if not exists public.customers (
  customer_id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  gender text not null,
  birthdate text not null, -- YYYY-MM-DD
  created_at text not null,
  city text,
  state text,
  zip_code text,
  customer_segment text,
  loyalty_tier text,
  is_active integer not null default 1
);

create table if not exists public.products (
  product_id bigint generated by default as identity primary key,
  sku text not null unique,
  product_name text not null,
  category text not null,
  price double precision not null,
  cost double precision not null,
  is_active integer not null default 1
);

create table if not exists public.orders (
  order_id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(customer_id),
  order_datetime text not null,
  billing_zip text,
  shipping_zip text,
  shipping_state text,
  payment_method text not null,
  device_type text not null,
  ip_country text not null,
  promo_used integer not null default 0,
  promo_code text,
  order_subtotal double precision not null,
  shipping_fee double precision not null,
  tax_amount double precision not null,
  order_total double precision not null,
  risk_score double precision not null,
  is_fraud integer not null default 0
);

create index if not exists idx_orders_customer on public.orders(customer_id);
create index if not exists idx_orders_datetime on public.orders(order_datetime);

create table if not exists public.order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id),
  product_id bigint not null references public.products(product_id),
  quantity integer not null,
  unit_price double precision not null,
  line_total double precision not null
);

create index if not exists idx_items_order on public.order_items(order_id);
create index if not exists idx_items_product on public.order_items(product_id);

create table if not exists public.shipments (
  shipment_id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(order_id),
  ship_datetime text not null,
  carrier text not null,
  shipping_method text not null,
  distance_band text not null,
  promised_days integer not null,
  actual_days integer not null,
  late_delivery integer not null default 0
);

create index if not exists idx_shipments_late on public.shipments(late_delivery);

create table if not exists public.product_reviews (
  review_id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(customer_id),
  product_id bigint not null references public.products(product_id),
  rating integer not null check (rating between 1 and 5),
  review_datetime text not null,
  review_text text,
  unique (customer_id, product_id)
);

create index if not exists idx_reviews_product on public.product_reviews(product_id);
create index if not exists idx_reviews_customer on public.product_reviews(customer_id);

-- Predictions table consumed by the app's priority queue page
create table if not exists public.order_predictions (
  order_id bigint primary key references public.orders(order_id),
  late_delivery_probability double precision not null,
  predicted_late_delivery integer not null,
  scored_at timestamptz not null default now()
);

create index if not exists idx_order_predictions_prob on public.order_predictions(late_delivery_probability desc);

-- Aggregate order item features (one row per order)
create or replace view public.vw_order_item_agg as
select
  oi.order_id,
  sum(oi.quantity)::int as total_quantity,
  count(distinct oi.product_id)::int as distinct_products,
  avg(oi.unit_price) as avg_unit_price
from public.order_items oi
group by oi.order_id;

-- Wide order features for scoring (one row per order)
create or replace view public.vw_order_features as
select
  o.order_id,
  o.customer_id,
  o.order_datetime,
  o.shipping_state,
  o.payment_method,
  o.device_type,
  o.ip_country,
  o.promo_used,
  o.order_subtotal,
  o.shipping_fee,
  o.tax_amount,
  o.order_total,
  o.risk_score,
  c.gender,
  c.birthdate,
  c.customer_segment,
  c.loyalty_tier,
  coalesce(a.total_quantity, 0) as total_quantity,
  coalesce(a.distinct_products, 0) as distinct_products,
  coalesce(a.avg_unit_price, 0) as avg_unit_price
from public.orders o
join public.customers c on c.customer_id = o.customer_id
left join public.vw_order_item_agg a on a.order_id = o.order_id;

-- Training data view (only orders with shipment labels)
create or replace view public.vw_training_late_delivery as
select
  f.*,
  s.promised_days,
  s.actual_days,
  s.late_delivery as label_late_delivery
from public.vw_order_features f
join public.shipments s on s.order_id = f.order_id;

